version: "3.8"

services:
    app:
        build: .
        container_name: HaarlemFestival
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel
        ports:
            - "80:80"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=localhost
            - DB_PORT=3306
            - DB_DATABASE=haarlemfestival
            - DB_USERNAME=haarlemfestival
            - DB_PASSWORD=!HaarlemFestival2025
        entrypoint: [ "sh", "-c", "composer install && php artisan key:generate && php artisan migrate --seed && php-fpm" ]

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: HaarlemFestival
            MYSQL_USER: haarlemfestival
            MYSQL_PASSWORD: !HaarlemFestival2025
        ports:
            - "3306:3306"
        networks:
            - laravel
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
